package store

import (
	"context"
	"fmt"
	"net/netip"
	"testing"
)

// The test network every derivation test runs against.
//
// IT TAKES ITS COUNTS AS PARAMETERS AND CARRIES BOTH ADDRESS FAMILIES, as the spec asks of
// every fixture: nothing in the code under test may presuppose how many interfaces or
// clients exist or which family an address is. The addresses below are example values a
// test is allowed to hold; the code under test reads them back out of the rows and never
// names one.
//
// Its shape: interfaceCount inside interfaces, each holding one IPv4 and one IPv6 prefix,
// plus one upstream interface with a gateway behind it; clientCount clients spread over the
// inside interfaces, alternating families, every third one leased and the rest seen only in
// flows. Flows of every direction are generated by flowsFor.

// testNetwork is a database with a network in it.
type testNetwork struct {
	db         *Store
	now        int64
	inside     []testInterface
	upstream   testInterface
	clients    []testClient
	ruleID     int64
	digestSeed int
}

type testInterface struct {
	id      int64
	device  string
	address string
	prefix  int64
	family  int64
	v6      string
}

type testClient struct {
	address     string
	interfaceID int64
	device      string
	leased      bool
	v6          bool
}

// referenceNow is a fixed instant in the middle of a UTC hour, so a test can place flows on
// either side of hour, day, week and month boundaries by arithmetic.
const referenceNow int64 = 1790000000

// newTestNetwork builds the network and returns it.
func newTestNetwork(t *testing.T, interfaceCount, clientCount int) *testNetwork {
	t.Helper()
	database, _ := openTestStore(t)
	ctx := context.Background()
	network := &testNetwork{db: database, now: referenceNow}

	for index := 0; index < interfaceCount; index++ {
		identifier := fmt.Sprintf("example_if_%d", index)
		device := fmt.Sprintf("exdev%d", index)
		id, err := database.UpsertInterface(ctx, Interface{
			Identifier: identifier, Device: device,
			Description: fmt.Sprintf("example description %d", index),
			LinkType:    "example-link", LinkKind: "other",
		}, network.now-86400)
		if err != nil {
			t.Fatalf("writing an interface: %v", err)
		}
		iface := testInterface{
			id: id, device: device, family: 4,
			address: fmt.Sprintf("10.%d.0.1", index+1), prefix: 24,
			v6: fmt.Sprintf("fd00:%x::1", index+1),
		}
		network.inside = append(network.inside, iface)
		bits4, bits6 := int64(24), int64(64)
		for _, address := range []InterfaceAddress{
			{InterfaceID: id, SourceField: SourceFieldAddr4, Address: iface.address, PrefixLength: &bits4, AddressFamily: 4},
			{InterfaceID: id, SourceField: SourceFieldAddr6, Address: iface.v6, PrefixLength: &bits6, AddressFamily: 6},
		} {
			if err := database.UpsertInterfaceAddress(ctx, address, network.now-86400); err != nil {
				t.Fatalf("writing an interface address: %v", err)
			}
		}
		// What discovery proposes from the same two addresses: their networks.
		if err := database.DetectNetworks(ctx, id, []netip.Prefix{
			netip.PrefixFrom(netip.MustParseAddr(iface.address), int(bits4)).Masked(),
			netip.PrefixFrom(netip.MustParseAddr(iface.v6), int(bits6)).Masked(),
		}, network.now-86400); err != nil {
			t.Fatalf("detecting the networks: %v", err)
		}
	}

	upstreamID, err := database.UpsertInterface(ctx, Interface{
		Identifier: "example_if_upstream", Device: "exdevup",
		Description: "example description upstream",
		LinkType:    "example-link", LinkKind: "other", IsUpstream: true,
	}, network.now-86400)
	if err != nil {
		t.Fatalf("writing the upstream interface: %v", err)
	}
	network.upstream = testInterface{id: upstreamID, device: "exdevup", address: "203.0.113.2", prefix: 24, family: 4}
	bits := int64(24)
	for _, address := range []InterfaceAddress{
		{InterfaceID: upstreamID, SourceField: SourceFieldAddr4, Address: "203.0.113.2", PrefixLength: &bits, AddressFamily: 4},
		{InterfaceID: upstreamID, SourceField: SourceFieldGateways, Address: "203.0.113.1", AddressFamily: 4},
	} {
		if err := database.UpsertInterfaceAddress(ctx, address, network.now-86400); err != nil {
			t.Fatalf("writing an upstream address: %v", err)
		}
	}
	if err := database.DetectNetworks(ctx, upstreamID, []netip.Prefix{
		netip.PrefixFrom(netip.MustParseAddr("203.0.113.2"), 24).Masked(),
	}, network.now-86400); err != nil {
		t.Fatalf("detecting the upstream network: %v", err)
	}

	network.ruleID, err = database.UpsertRule(ctx, Rule{
		PfLabel: "example-rule-label", Description: "example rule", Action: "pass",
	}, network.now-86400)
	if err != nil {
		t.Fatalf("writing a rule: %v", err)
	}

	leaseProvider, err := database.ProviderID(ctx, "dhcp_lease", "dnsmasq")
	if err != nil {
		t.Fatalf("looking up a lease provider: %v", err)
	}
	for index := 0; index < clientCount; index++ {
		iface := network.inside[index%len(network.inside)]
		host := 10 + index/len(network.inside)
		client := testClient{interfaceID: iface.id, device: iface.device, leased: index%3 == 0,
			v6: index%2 == 1}
		if client.v6 {
			client.address = fmt.Sprintf("fd00:%x::%x", (index%len(network.inside))+1, host)
		} else {
			client.address = fmt.Sprintf("10.%d.0.%d", (index%len(network.inside))+1, host)
		}
		if client.leased {
			mac := fmt.Sprintf("00:00:00:00:%02x:%02x", index/256, index%256)
			clientID, err := database.UpsertClient(ctx, Client{
				Identity:    ClientIdentity{Kind: IdentityMAC, Key: mac},
				InterfaceID: &iface.id, MAC: &mac, LastAddress: &client.address,
			}, network.now-3600)
			if err != nil {
				t.Fatalf("writing a leased client: %v", err)
			}
			expiry := network.now + 3600
			if err := database.InsertDHCPLease(ctx, leaseProvider, DHCPLease{
				ClientID: &clientID, Backend: "dnsmasq", Address: client.address, MAC: &mac,
				LeaseState: "active", InterfaceID: &iface.id,
				GenerationKey: GenerationKeyOf(nil, &expiry, 0), ExpiresAt: &expiry,
				ObservedAt: network.now - 3600,
			}); err != nil {
				t.Fatalf("writing a lease: %v", err)
			}
		}
		network.clients = append(network.clients, client)
	}
	return network
}

// outside returns the k-th outside address of a family.
func outside(k int, v6 bool) string {
	if v6 {
		return fmt.Sprintf("2001:db8::%x", k+1)
	}
	return fmt.Sprintf("198.51.100.%d", (k%250)+1)
}

// networkFlow is one generated record.
type networkFlow struct {
	observedAt int64
	device     string
	direction  string
	src, dst   string
	dstPort    *int64
	protocol   string
	action     string
	reason     *string
	bytes      int64
	ruleID     *int64
	ingestedAt int64
}

// insert stores the records unplaced, as the collector does.
func (n *testNetwork) insert(t *testing.T, specs []networkFlow) []string {
	t.Helper()
	ctx := context.Background()
	var addresses []string
	for _, spec := range specs {
		n.digestSeed++
		version := int64(4)
		if containsColon(spec.src) {
			version = 6
		}
		rid := "example-rule-label"
		state := LookupNotFound
		if spec.ruleID != nil {
			state = LookupResolved
		}
		ingested := spec.ingestedAt
		if ingested == 0 {
			// Written a second before the refresh that follows, as a pass's rows are: a row
			// stamped in the same second as a refresh is stale to it by rule 3.
			ingested = n.now - 1
		}
		if err := n.db.InsertFlow(ctx, Flow{
			LogDigest: fmt.Sprintf("example-digest-%d", n.digestSeed), ObservedAt: spec.observedAt,
			IngestedAt: ingested, InterfaceDevice: spec.device, InterfaceLookupState: LookupResolved,
			SrcAddress: spec.src, DstAddress: spec.dst, DstPort: spec.dstPort, Protocol: spec.protocol,
			IPVersion: version, Action: spec.action, Direction: spec.direction, LogReason: spec.reason,
			PacketBytes: spec.bytes, Rid: &rid, RuleID: spec.ruleID, RuleLookupState: state,
		}); err != nil {
			t.Fatalf("writing a flow: %v", err)
		}
		addresses = append(addresses, spec.src, spec.dst)
	}
	return addresses
}

func containsColon(text string) bool {
	for index := 0; index < len(text); index++ {
		if text[index] == ':' {
			return true
		}
	}
	return false
}

// flowsFor generates count records ending at the network's now, spread back over span
// seconds, of every direction: a client to the outside logged inbound on its own interface,
// the outside to a client logged on the upstream interface, a client to a client of another
// interface, and an unsolicited packet to the firewall's own upstream address. Blocked
// records carry each kind of reason.
func (n *testNetwork) flowsFor(count int, span int64) []networkFlow {
	reasons := []*string{ptr(LogReasonMatch), ptr("state-mismatch"), nil, ptr("unknown(16)")}
	var specs []networkFlow
	for index := 0; index < count; index++ {
		client := n.clients[index%len(n.clients)]
		other := n.clients[(index*7+3)%len(n.clients)]
		observed := n.now - (int64(index) * span / int64(count+1)) - 1
		port := int64(443 + index%3)
		spec := networkFlow{observedAt: observed, protocol: "tcp", action: "pass",
			bytes: int64(60 + (index*37)%1400), dstPort: &port}
		if index%5 == 0 {
			spec.action = "block"
			spec.reason = reasons[(index/5)%len(reasons)]
		}
		// A reject is a refusal too, and a record whose action could not be named is neither
		// allowed nor blocked.
		if index%13 == 0 {
			spec.action = "reject"
		}
		if index%17 == 0 {
			spec.action = "unknown"
		}
		if index%4 == 0 {
			spec.ruleID = &n.ruleID
		}
		if index%9 == 0 {
			spec.protocol, spec.dstPort = "icmp", nil
		}
		switch index % 4 {
		case 0, 1:
			spec.device, spec.direction = client.device, "in"
			spec.src, spec.dst = client.address, outside(index, client.v6)
		case 2:
			spec.device, spec.direction = n.upstream.device, "in"
			spec.src, spec.dst = outside(index, client.v6), client.address
		default:
			if other.v6 == client.v6 && other.address != client.address {
				spec.device, spec.direction = client.device, "in"
				spec.src, spec.dst = client.address, other.address
			} else {
				spec.device, spec.direction = n.upstream.device, "in"
				spec.src, spec.dst = outside(index, false), n.upstream.address
			}
		}
		specs = append(specs, spec)
	}
	return specs
}

func ptr[T any](value T) *T { return &value }

// classifyAndRefresh runs what the collector runs after a pass.
func (n *testNetwork) classifyAndRefresh(t *testing.T, addresses []string) Refresh {
	t.Helper()
	ctx := context.Background()
	if _, err := n.db.Reclassify(ctx, addresses, n.now); err != nil {
		t.Fatalf("classifying: %v", err)
	}
	refresh, err := n.db.RefreshAggregates(ctx, 0, n.now, nil)
	if err != nil {
		t.Fatalf("refreshing: %v", err)
	}
	return refresh
}

// populated returns a network with flows over the last span seconds, classified and
// refreshed.
func populated(t *testing.T, interfaceCount, clientCount, flowCount int, span int64) *testNetwork {
	t.Helper()
	network := newTestNetwork(t, interfaceCount, clientCount)
	addresses := network.insert(t, network.flowsFor(flowCount, span))
	network.classifyAndRefresh(t, addresses)
	return network
}

// queryInt reads one integer.
func queryInt(t *testing.T, database *Store, query string, arguments ...any) int64 {
	t.Helper()
	var value int64
	if err := database.DB().QueryRowContext(context.Background(), query, arguments...).Scan(&value); err != nil {
		t.Fatalf("%s: %v", query, err)
	}
	return value
}

// foreignKeyViolations runs PRAGMA foreign_key_check.
func foreignKeyViolations(t *testing.T, database *Store) int {
	t.Helper()
	rows, err := database.DB().QueryContext(context.Background(), "PRAGMA foreign_key_check")
	if err != nil {
		t.Fatalf("running the foreign-key check: %v", err)
	}
	defer func() { _ = rows.Close() }()
	count := 0
	for rows.Next() {
		count++
	}
	return count
}
