-- opnview — deterministic seed for the schema checks.
--
-- Pure SQL, generated by recursive common table expressions. No Go code, no
-- external generator, and no address literal: every address is synthesised
-- from a counter at generation time and carries no addressing-plan meaning.
-- Nothing in the schema or in the seven screen queries interprets an address;
-- segment membership is carried by foreign keys, never by an address range.
--
-- Bound parameters, all supplied by the caller. The row counts are parameters
-- precisely so the checks can re-run the whole file against a different number
-- of segments, devices and flows and show that nothing assumes the defaults.
--
--   :now          the instant the seed pretends to run, UTC epoch seconds
--   :segments     how many segments to discover        (must be >= 2)
--   :devices      how many devices to observe          (must be > :segments)
--   :rules        how many firewall rules to discover  (must be >= 2)
--   :flow_rows    rows in flow, the largest growing table
--   :alerts       rows in security_event
--   :pair_rows    logical pairs in pair_volume_observation; each one is
--                 offered twice, once per direction, and must collapse to one
--
-- Running the file twice against the same fresh database produces identical
-- row counts per table.

PRAGMA foreign_keys = ON;

BEGIN IMMEDIATE;

-- ---------------------------------------------------------------------------
-- The provider registry already holds one row per surveyed implementation,
-- created by migration 0002 with none active. A probe round has now run, so
-- the seed marks exactly one provider active per kind -- the one this
-- pretend-installation reads. The partial unique index rejects a second.
--
-- Everything below that needs a provider looks it up by kind and activeness,
-- never by name: no other statement in this file tests a provider key.
-- ---------------------------------------------------------------------------
UPDATE provider SET is_active = 1
WHERE (kind, provider_key) IN (
    VALUES ('firewall_log', 'pf'),
           ('security_event', 'suricata'),
           ('flow_volume', 'insight'),
           ('dhcp_lease', 'kea'),
           ('dns_lookup', 'unbound'),
           ('geo_asn', 'maxmind_geolite2')
);

-- ---------------------------------------------------------------------------
-- Segments. The last one is discovered as a tunnel, every other as a VLAN, so
-- both kinds are present whatever :segments is. link_kind is derived from the
-- discovered link type and from nothing else: no name is inspected anywhere.
-- ---------------------------------------------------------------------------
WITH RECURSIVE counter (n) AS (
    SELECT 1
    UNION ALL
    SELECT n + 1 FROM counter WHERE n < :segments
),
discovered AS (
    SELECT
        n,
        CASE WHEN n = :segments THEN 'tunnel' ELSE 'vlan' END AS discovered_link_type
    FROM counter
)
INSERT INTO segment (id, interface_identifier, device_name, discovered_description,
                     user_label, discovered_link_type, link_kind, vlan_tag,
                     address_family, first_seen_at, last_seen_at)
SELECT
    n,
    printf('interface-identifier-%d', n),
    printf('device-%d', n),
    printf('discovered-description-%d', n),
    NULL,
    discovered_link_type,
    CASE discovered_link_type
        WHEN 'tunnel' THEN 'tunnel'
        WHEN 'vlan' THEN 'vlan'
        ELSE 'other'
    END,
    100 + n,
    4,
    :now - 8640000,
    :now
FROM discovered;

-- The interface map covers every discovered segment. Flows carrying a raw
-- device name absent from this table exercise the "not found" state.
INSERT INTO interface_map (device_name, description, segment_id, discovered_at)
SELECT device_name, discovered_description, id, :now - 8640000 FROM segment;

-- ---------------------------------------------------------------------------
-- Firewall rules.
-- ---------------------------------------------------------------------------
WITH RECURSIVE counter (n) AS (
    SELECT 1
    UNION ALL
    SELECT n + 1 FROM counter WHERE n < :rules
)
INSERT INTO rule (id, pf_label, description, action, direction, is_automatic, discovered_at)
SELECT
    n,
    printf('rule-label-%d', n),
    printf('rule-description-%d', n),
    CASE WHEN n % 4 = 0 THEN 'block' ELSE 'pass' END,
    CASE WHEN n % 2 = 0 THEN 'in' ELSE 'out' END,
    CASE WHEN n % 9 = 0 THEN 1 ELSE 0 END,
    :now - 8640000
FROM counter;

-- ---------------------------------------------------------------------------
-- Devices.
--
-- The first octet of the MAC is 0x10 plus twice a counter modulo 8, so the
-- second hex digit walks 0, 2, 4, 6, 8, a, c, e. Four of those carry the IEEE
-- locally-administered bit (2, 6, a, e) and are randomised identities; the
-- other four (0, 4, 8, c) are globally administered burned-in addresses and
-- must NOT be marked unstable. Both halves are therefore present in every run.
--
-- Every tenth device has no MAC at all: the filter log carries none, so a
-- device seen only in flows must still be representable. Its identity falls to
-- the last level of the cascade, the address within its segment over a
-- validity interval.
-- ---------------------------------------------------------------------------
WITH RECURSIVE counter (n) AS (
    SELECT 1
    UNION ALL
    SELECT n + 1 FROM counter WHERE n < :devices
),
generated AS (
    SELECT
        n,
        ((n - 1) % :segments) + 1 AS segment_id,
        CASE
            WHEN n % 10 = 0 THEN NULL
            ELSE printf('%02x:%02x:%02x:%02x:%02x:%02x',
                        16 + (((n - 1) % 8) * 2),
                        (n * 7) % 256, (n * 13) % 256,
                        (n * 29) % 256, (n * 37) % 256, n % 256)
        END AS mac,
        printf('%d.%d.%d.%d',
               (n / 16777216) % 256, (n / 65536) % 256, (n / 256) % 256, n % 256) AS address
    FROM counter
)
INSERT INTO device (id, identity_kind, identity_key, segment_id, mac, hostname,
                    vendor_hint, last_address, first_seen_at, last_seen_at)
SELECT
    n,
    CASE
        WHEN mac IS NULL THEN 'address_in_segment'
        WHEN n % 3 = 1 THEN 'dhcp_client_id'
        ELSE 'mac'
    END,
    CASE
        WHEN mac IS NULL THEN printf('%d|%s|%d', segment_id, address, :now - 8640000)
        WHEN n % 3 = 1 THEN printf('client-identity-%d', n)
        ELSE mac
    END,
    segment_id,
    mac,
    CASE WHEN mac IS NULL THEN NULL ELSE printf('host-%d', n) END,
    printf('vendor-hint-%d', n % 17),
    address,
    :now - 8640000,
    :now
FROM generated;

-- One address, reissued to a different machine after the first lease expired.
-- The two observations must stay two devices: the address level of the cascade
-- keys on the lease validity start, so the reissue produces a different
-- identity_key and nothing merges.
WITH reissued AS (
    SELECT printf('%d.%d.%d.%d',
                  ((:devices + 1) / 16777216) % 256, ((:devices + 1) / 65536) % 256,
                  ((:devices + 1) / 256) % 256, (:devices + 1) % 256) AS address
)
INSERT INTO device (id, identity_kind, identity_key, segment_id, mac, hostname,
                    vendor_hint, last_address, first_seen_at, last_seen_at)
SELECT :devices + 1, 'address_in_segment',
       printf('%d|%s|%d', 1, address, :now - 17280000),
       1, NULL, NULL, NULL, address, :now - 17280000, :now - 16416000
FROM reissued
UNION ALL
SELECT :devices + 2, 'address_in_segment',
       printf('%d|%s|%d', 1, address, :now - 2592000),
       1, NULL, NULL, NULL, address, :now - 2592000, :now
FROM reissued;

-- ---------------------------------------------------------------------------
-- DHCP leases. One per device that has a MAC, spread back over five months so
-- that a finite retention horizon has something to purge, plus the two leases
-- of the reissued address above.
-- ---------------------------------------------------------------------------
INSERT INTO dhcp_lease (device_id, backend, address, mac, hostname, client_id, duid, iaid,
                        vendor_hint, lease_state, segment_id, starts_at, expires_at, observed_at)
SELECT
    id,
    'kea',
    last_address,
    mac,
    hostname,
    CASE WHEN identity_kind = 'dhcp_client_id' THEN identity_key END,
    NULL,
    NULL,
    vendor_hint,
    'active',
    segment_id,
    :now - ((id % 8) * 1728000) - 3600,
    :now - ((id % 8) * 1728000) + 86400,
    :now - ((id % 8) * 1728000)
FROM device
WHERE mac IS NOT NULL;

INSERT INTO dhcp_lease (device_id, backend, address, mac, hostname, client_id, duid, iaid,
                        vendor_hint, lease_state, segment_id, starts_at, expires_at, observed_at)
SELECT id, 'kea', last_address, NULL, NULL, NULL, NULL, NULL, NULL,
       'expired', segment_id, :now - 17280000, :now - 16416000, :now - 16416000
FROM device WHERE id = :devices + 1
UNION ALL
SELECT id, 'kea', last_address, NULL, NULL, NULL, NULL, NULL, NULL,
       'active', segment_id, :now - 2592000, :now + 86400, :now
FROM device WHERE id = :devices + 2;

-- ---------------------------------------------------------------------------
-- Flows — the largest growing table, one row per filter-log record.
--
-- Timestamps walk backwards from :now in 97-second steps, so the seeded
-- history is deterministic, dense near the present and long enough for a
-- 90-day retention horizon to bite.
--
-- Shape of the generated population:
--   i % 3 = 0   east-west: both endpoints sit in a discovered segment
--   i % 3 <> 0  north-south: the destination is outside every segment
--   i % 3 = 2   the flow will also carry a site-name attribution
--   i % 7 = 0   blocked
--   i % 11 = 0  the rid matches no known rule  -> rule_lookup_state not_found
--   i % 13 = 0  the raw device name is absent from the interface map
-- The moduli are coprime with :devices in the default run, so every device
-- sees flows of every kind rather than one kind only.
-- ---------------------------------------------------------------------------
WITH RECURSIVE counter (i) AS (
    SELECT 1
    UNION ALL
    SELECT i + 1 FROM counter WHERE i < :flow_rows
),
chosen AS (
    SELECT
        i,
        :now - (i * 97)                                      AS observed_at,
        ((i - 1) % :devices) + 1                             AS src_device_id,
        CASE WHEN i % 3 = 0 THEN (i % :devices) + 1 END      AS dst_device_id,
        i % 7 = 0                                            AS is_blocked,
        i % 11 = 0                                           AS rule_missing,
        i % 13 = 0                                           AS interface_missing
    FROM counter
),
placed AS (
    SELECT
        i, observed_at, src_device_id, dst_device_id,
        is_blocked, rule_missing, interface_missing,
        ((src_device_id - 1) % :segments) + 1 AS src_segment_id,
        CASE WHEN dst_device_id IS NOT NULL
             THEN ((dst_device_id - 1) % :segments) + 1 END AS dst_segment_id,
        printf('%d.%d.%d.%d',
               (src_device_id / 16777216) % 256, (src_device_id / 65536) % 256,
               (src_device_id / 256) % 256, src_device_id % 256) AS src_address,
        CASE
            WHEN dst_device_id IS NOT NULL THEN
                printf('%d.%d.%d.%d',
                       (dst_device_id / 16777216) % 256, (dst_device_id / 65536) % 256,
                       (dst_device_id / 256) % 256, dst_device_id % 256)
            ELSE
                printf('%d.%d.%d.%d',
                       ((1000000 + (i % 4000)) / 16777216) % 256,
                       ((1000000 + (i % 4000)) / 65536) % 256,
                       ((1000000 + (i % 4000)) / 256) % 256,
                       (1000000 + (i % 4000)) % 256)
        END AS dst_address
    FROM chosen
)
INSERT INTO flow (id, log_digest, observed_at, ingested_at, interface_device,
                  interface_lookup_state, src_segment_id, dst_segment_id,
                  src_device_id, dst_device_id, src_address, dst_address,
                  src_port, dst_port, protocol, ip_version, action, direction,
                  packet_bytes, rid, rule_id, rule_lookup_state, traffic_scope)
SELECT
    i,
    printf('log-digest-%d', i),
    observed_at,
    observed_at + 5,
    CASE WHEN interface_missing
         THEN printf('unmapped-device-%d', i)
         ELSE printf('device-%d', src_segment_id) END,
    CASE WHEN interface_missing THEN 'not_found' ELSE 'resolved' END,
    src_segment_id,
    dst_segment_id,
    src_device_id,
    dst_device_id,
    src_address,
    dst_address,
    1024 + ((i * 17) % 64000),
    1 + ((i * 13) % 65000),
    CASE WHEN i % 2 = 0 THEN 'tcp' ELSE 'udp' END,
    4,
    CASE WHEN is_blocked THEN 'block' ELSE 'pass' END,
    CASE WHEN i % 2 = 0 THEN 'in' ELSE 'out' END,
    40 + ((i * 37) % 1460),
    CASE WHEN rule_missing
         THEN printf('orphan-rule-label-%d', i)
         ELSE printf('rule-label-%d', ((i - 1) % :rules) + 1) END,
    CASE WHEN rule_missing THEN NULL ELSE ((i - 1) % :rules) + 1 END,
    CASE WHEN rule_missing THEN 'not_found' ELSE 'resolved' END,
    -- Segment membership and nothing else. The CHECK on the column rejects any
    -- other value, so this expression cannot drift from the schema's.
    CASE WHEN src_segment_id IS NOT NULL AND dst_segment_id IS NOT NULL
         THEN 'east_west' ELSE 'north_south' END
FROM placed;

-- ---------------------------------------------------------------------------
-- Resolver lookups, and the site names inferred from them.
--
-- Only the north-south flows with i % 3 = 2 get an attribution, so every
-- device also has unattributed flows: the Device screen must return those with
-- their address, country and operator and a null site name rather than
-- dropping them, and the attribution rate must be below 100 per cent.
-- ---------------------------------------------------------------------------
INSERT INTO dns_resolution (id, lookup_uuid, client_address, device_id, domain,
                            resolver, action, answer_source, rcode,
                            looked_up_at, ingested_at)
SELECT
    id,
    printf('lookup-uuid-%d', id),
    src_address,
    src_device_id,
    printf('name-%d.example-zone-%d.invalid', id % 997, id % 13),
    'unbound',
    'pass',
    CASE WHEN id % 5 = 0 THEN 'cache' ELSE 'recursion' END,
    'NOERROR',
    observed_at - (1 + (id % 30)),
    observed_at
FROM flow
WHERE id % 3 = 2;

INSERT INTO domain_attribution (flow_id, dns_resolution_id, site_name,
                                correlation_delay_seconds, attributed_at)
SELECT id, id, printf('name-%d.example-zone-%d.invalid', id % 997, id % 13),
       1 + (id % 30), observed_at
FROM flow
WHERE id % 3 = 2;

-- ---------------------------------------------------------------------------
-- Geo / ASN cache, one row per synthesised external address. Roughly one in
-- thirty-seven is a modelled cache miss rather than an absent row, so the Map
-- and Device screens can show that the enrichment did not answer instead of
-- silently dropping the volume.
-- ---------------------------------------------------------------------------
WITH RECURSIVE counter (j) AS (
    SELECT 0
    UNION ALL
    SELECT j + 1 FROM counter WHERE j < 3999
),
generated AS (
    SELECT
        j,
        printf('%d.%d.%d.%d',
               ((1000000 + j) / 16777216) % 256, ((1000000 + j) / 65536) % 256,
               ((1000000 + j) / 256) % 256, (1000000 + j) % 256) AS address,
        char(65 + (j % 26), 65 + ((j / 26) % 26)) AS country_code,
        j % 37 = 0 AS is_miss
    FROM counter
)
INSERT INTO geo_asn (address, provider_id, lookup_state, country_code, country_name,
                     latitude, longitude, asn, operator, dataset_build_at, looked_up_at)
SELECT
    address,
    (SELECT id FROM provider WHERE kind = 'geo_asn' AND is_active = 1),
    CASE WHEN is_miss THEN 'miss' ELSE 'resolved' END,
    CASE WHEN is_miss THEN NULL ELSE country_code END,
    CASE WHEN is_miss THEN NULL ELSE printf('country-name-%s', country_code) END,
    CASE WHEN is_miss THEN NULL ELSE ((j % 180) - 90) * 1.0 END,
    CASE WHEN is_miss THEN NULL ELSE ((j % 360) - 180) * 1.0 END,
    CASE WHEN is_miss THEN NULL ELSE 1000 + j END,
    CASE WHEN is_miss THEN NULL ELSE printf('operator-%d', j % 97) END,
    CASE WHEN is_miss THEN NULL ELSE :now - 604800 END,
    :now - ((j % 100) * 86400)
FROM generated;

-- ---------------------------------------------------------------------------
-- Security events, and the per-provider rule-info cache that gives them a
-- severity.
--
-- Every event is attributed to the active provider of the security_event kind
-- and carries the key that provider guarantees stable -- for this one, the eve
-- file id and the byte offset inside it, composed into a single text key by
-- the collector. The ingestion coordinate is not stored as columns here; that
-- is eve_ingest_cursor's concern.
--
-- Rule identities are text. Forty-nine of the fifty are numeric strings and
-- one is deliberately NON-NUMERIC, so a provider whose rules are named rather
-- than numbered is exercised. Ten of the numeric ones are absent from the
-- cache, so the Alerts screen has to render an explicit unknown severity.
--
-- normalised_severity is NULL on every row: Suricata ships no severity inside
-- the event (survey, gap 3), and this restructuring changes nothing about it.
-- ---------------------------------------------------------------------------
WITH RECURSIVE counter (m) AS (
    SELECT 1
    UNION ALL
    SELECT m + 1 FROM counter WHERE m < :alerts
),
generated AS (
    SELECT
        m,
        -- Dense over the last few days, then stretched back over four months,
        -- so the recent window is busy enough to exercise the Alerts screen
        -- and a finite retention horizon still has something to purge.
        :now - (m * 601) - (max(m - 250, 0) * 40000) AS occurred_at,
        ((m - 1) % :devices) + 1                     AS src_device_id,
        -- Three rotated files whatever :alerts is, so the ingestion cursor
        -- always has a watermark per file to record.
        1 + (((m - 1) * 3) / :alerts)                AS file_number,
        m * 4096                                     AS byte_position
    FROM counter
)
INSERT INTO security_event (id, provider_id, provider_event_key, occurred_at, ingested_at,
                            rule_identity, signature, event_action, normalised_severity,
                            src_address, src_port, dst_address, dst_port, protocol,
                            in_interface_device, src_device_id, src_segment_id, flow_ref)
SELECT
    m,
    (SELECT id FROM provider WHERE kind = 'security_event' AND is_active = 1),
    printf('eve-file-%d:%d', file_number, byte_position),
    occurred_at,
    occurred_at + 30,
    CASE WHEN m % 50 = 3
         THEN 'named-rule-identity-alpha'
         ELSE printf('%d', 1000000 + (m % 50)) END,
    printf('signature-text-%d', m % 50),
    CASE WHEN m % 4 = 0 THEN 'blocked' ELSE 'allowed' END,
    NULL,
    printf('%d.%d.%d.%d',
           (src_device_id / 16777216) % 256, (src_device_id / 65536) % 256,
           (src_device_id / 256) % 256, src_device_id % 256),
    1024 + ((m * 19) % 64000),
    printf('%d.%d.%d.%d',
           ((1000000 + (m % 4000)) / 16777216) % 256,
           ((1000000 + (m % 4000)) / 65536) % 256,
           ((1000000 + (m % 4000)) / 256) % 256,
           (1000000 + (m % 4000)) % 256),
    1 + ((m * 7) % 65000),
    CASE WHEN m % 2 = 0 THEN 'tcp' ELSE 'udp' END,
    printf('device-%d', ((src_device_id - 1) % :segments) + 1),
    src_device_id,
    ((src_device_id - 1) % :segments) + 1,
    NULL
FROM generated;

-- The cache. normalised_severity is opnview's ordered vocabulary;
-- provider_severity keeps the raw numeric string the provider reported, so the
-- normalisation stays auditable. The mapping 1..4 -> critical, high, medium,
-- low is documented in docs/data-model.md.
WITH RECURSIVE counter (x) AS (
    SELECT 0
    UNION ALL
    SELECT x + 1 FROM counter WHERE x < 39
),
raw AS (
    SELECT x, 1 + (x % 4) AS provider_severity FROM counter
)
INSERT INTO provider_rule_info (provider_id, rule_identity, normalised_severity,
                                provider_severity, category, rule_source, fetched_at)
SELECT
    (SELECT id FROM provider WHERE kind = 'security_event' AND is_active = 1),
    CASE WHEN x = 3 THEN 'named-rule-identity-alpha' ELSE printf('%d', 1000000 + x) END,
    CASE provider_severity
        WHEN 1 THEN 'critical'
        WHEN 2 THEN 'high'
        WHEN 3 THEN 'medium'
        ELSE 'low'
    END,
    printf('%d', provider_severity),
    printf('category-%d', x % 7),
    printf('rule-source-%d', x % 3),
    :now - 3600
FROM raw;

-- ---------------------------------------------------------------------------
-- eve.json ingestion cursor: one watermark per rotated file, with the rotation
-- state. 'lost' is the case where rotation discarded the file the watermark
-- referred to, so the gap is permanent and recorded as such.
--
-- This is a DIFFERENT guarantee from the one on security_event. The unique key
-- here answers "where did the reader stop in this file"; the unique key there
-- answers "have I already stored this event". Merging them would lose one of
-- the two.
-- ---------------------------------------------------------------------------
WITH RECURSIVE counter (m) AS (
    SELECT 1
    UNION ALL
    SELECT m + 1 FROM counter WHERE m < :alerts
),
watermarks AS (
    SELECT 1 + (((m - 1) * 3) / :alerts) AS file_number, m * 4096 AS byte_position
    FROM counter
)
INSERT INTO eve_ingest_cursor (file_id, byte_offset, file_sequence, rotation_state, observed_at)
SELECT 'eve-file-0', 0, 0, 'lost', :now - 604800
UNION ALL
SELECT printf('eve-file-%d', file_number), max(byte_position), file_number,
       CASE WHEN file_number = 3 THEN 'current' ELSE 'rotated' END, :now
FROM watermarks
GROUP BY file_number;

-- ---------------------------------------------------------------------------
-- NetFlow per-pair volume.
--
-- Insight writes each flow once per interface and once per direction, with
-- source and destination swapped on the outbound one, so the seed offers every
-- pair twice — exactly the direction doubling the survey describes. The
-- de-duplication key collapses them to one logical volume: after this
-- statement the table holds :pair_rows rows, not twice that.
-- ---------------------------------------------------------------------------
WITH RECURSIVE counter (p) AS (
    SELECT 1
    UNION ALL
    SELECT p + 1 FROM counter WHERE p < :pair_rows
),
pairs AS (
    SELECT
        p,
        (((:now / 86400) - (p % 120)) * 86400) AS day_start_at,
        printf('%d.%d.%d.%d',
               ((((p - 1) % :devices) + 1) / 16777216) % 256,
               ((((p - 1) % :devices) + 1) / 65536) % 256,
               ((((p - 1) % :devices) + 1) / 256) % 256,
               (((p - 1) % :devices) + 1) % 256) AS local_address,
        printf('%d.%d.%d.%d',
               ((1000000 + p) / 16777216) % 256, ((1000000 + p) / 65536) % 256,
               ((1000000 + p) / 256) % 256, (1000000 + p) % 256) AS peer_address
    FROM counter
),
doubled AS (
    SELECT p, day_start_at, local_address AS a, peer_address AS b, 'out' AS observed_direction
    FROM pairs
    UNION ALL
    SELECT p, day_start_at, peer_address AS a, local_address AS b, 'in' AS observed_direction
    FROM pairs
)
INSERT OR IGNORE INTO pair_volume_observation
    (day_start_at, endpoint_low, endpoint_high, service_port, protocol,
     octets, packets, observed_direction, observed_interface_device,
     last_seen_at, ingested_at)
SELECT
    day_start_at,
    min(a, b),
    max(a, b),
    1 + (p % 1000),
    CASE WHEN p % 2 = 0 THEN 'tcp' ELSE 'udp' END,
    1000.0 + p,
    10.0 + (p % 50),
    observed_direction,
    printf('device-%d', ((p - 1) % :segments) + 1),
    day_start_at + 86399,
    :now
FROM doubled
ORDER BY p, observed_direction;

-- ---------------------------------------------------------------------------
-- The four pre-computed aggregates.
--
-- They are computed from opnview's own stored flows, not from any Insight
-- column: per-address-pair volume on the firewall exists only at daily
-- resolution and only for 62 days, and per-source totals at 300 s resolution
-- are kept one hour (survey, data source 3), so the 1 h and 24 h periods can
-- only come from opnview's own history. computed_at is the freshness stamp.
-- ---------------------------------------------------------------------------
INSERT INTO volume_aggregate_1h (period_start_at, period_end_at, src_segment_id,
                                 dst_segment_id, peer_address, traffic_scope,
                                 bytes, allowed_connections, blocked_connections, computed_at)
SELECT
    (observed_at / 3600) * 3600,
    (observed_at / 3600) * 3600 + 3600,
    src_segment_id,
    dst_segment_id,
    CASE WHEN dst_segment_id IS NULL THEN dst_address END,
    traffic_scope,
    sum(packet_bytes),
    sum(CASE WHEN action <> 'block' THEN 1 ELSE 0 END),
    sum(CASE WHEN action = 'block' THEN 1 ELSE 0 END),
    :now
FROM flow
WHERE src_segment_id IS NOT NULL
GROUP BY 1, 2, 3, 4, 5, 6;

INSERT INTO volume_aggregate_24h (period_start_at, period_end_at, src_segment_id,
                                  dst_segment_id, peer_address, traffic_scope,
                                  bytes, allowed_connections, blocked_connections, computed_at)
SELECT
    (observed_at / 86400) * 86400,
    (observed_at / 86400) * 86400 + 86400,
    src_segment_id,
    dst_segment_id,
    CASE WHEN dst_segment_id IS NULL THEN dst_address END,
    traffic_scope,
    sum(packet_bytes),
    sum(CASE WHEN action <> 'block' THEN 1 ELSE 0 END),
    sum(CASE WHEN action = 'block' THEN 1 ELSE 0 END),
    :now
FROM flow
WHERE src_segment_id IS NOT NULL
GROUP BY 1, 2, 3, 4, 5, 6;

INSERT INTO volume_aggregate_7d (period_start_at, period_end_at, src_segment_id,
                                 dst_segment_id, peer_address, traffic_scope,
                                 bytes, allowed_connections, blocked_connections, computed_at)
SELECT
    (observed_at / 604800) * 604800,
    (observed_at / 604800) * 604800 + 604800,
    src_segment_id,
    dst_segment_id,
    CASE WHEN dst_segment_id IS NULL THEN dst_address END,
    traffic_scope,
    sum(packet_bytes),
    sum(CASE WHEN action <> 'block' THEN 1 ELSE 0 END),
    sum(CASE WHEN action = 'block' THEN 1 ELSE 0 END),
    :now
FROM flow
WHERE src_segment_id IS NOT NULL
GROUP BY 1, 2, 3, 4, 5, 6;

INSERT INTO volume_aggregate_30d (period_start_at, period_end_at, src_segment_id,
                                  dst_segment_id, peer_address, traffic_scope,
                                  bytes, allowed_connections, blocked_connections, computed_at)
SELECT
    (observed_at / 2592000) * 2592000,
    (observed_at / 2592000) * 2592000 + 2592000,
    src_segment_id,
    dst_segment_id,
    CASE WHEN dst_segment_id IS NULL THEN dst_address END,
    traffic_scope,
    sum(packet_bytes),
    sum(CASE WHEN action <> 'block' THEN 1 ELSE 0 END),
    sum(CASE WHEN action = 'block' THEN 1 ELSE 0 END),
    :now
FROM flow
WHERE src_segment_id IS NOT NULL
GROUP BY 1, 2, 3, 4, 5, 6;

-- ---------------------------------------------------------------------------
-- Provider availability. One row per registry row already exists, created by
-- migration 0002 in the "not yet probed" state; the seed records what a probe
-- round found. Every kind therefore carries both halves of the picture: which
-- implementations are reachable, and which single one is active.
--
-- The active security-event provider is present but disabled and the active
-- DNS-lookup provider is unavailable, so the screens have both degraded states
-- to render while their kinds still have an active provider. The
-- implementations this installation does not run are 'unavailable' -- a
-- modelled state, not an absent row.
-- ---------------------------------------------------------------------------
UPDATE source_availability
SET state = 'reachable', probe = 'GET /api/diagnostics/firewall/log',
    detail = NULL, checked_at = :now
WHERE provider_id IN (SELECT id FROM provider WHERE kind = 'firewall_log' AND is_active = 1);

UPDATE source_availability
SET state = 'present_but_disabled', probe = 'GET /api/ids/service/status',
    detail = 'status reported stopped', checked_at = :now
WHERE provider_id IN (SELECT id FROM provider WHERE kind = 'security_event' AND is_active = 1);

UPDATE source_availability
SET state = 'reachable', probe = 'GET /api/diagnostics/netflow/is_enabled',
    detail = 'local collection enabled', checked_at = :now
WHERE provider_id IN (SELECT id FROM provider WHERE kind = 'flow_volume' AND is_active = 1);

UPDATE source_availability
SET state = 'reachable', probe = 'GET /api/kea/service/status',
    detail = NULL, checked_at = :now
WHERE provider_id IN (SELECT id FROM provider WHERE kind = 'dhcp_lease' AND is_active = 1);

UPDATE source_availability
SET state = 'unavailable', probe = 'GET /api/unbound/overview/is_enabled',
    detail = 'query reporting is off', checked_at = :now
WHERE provider_id IN (SELECT id FROM provider WHERE kind = 'dns_lookup' AND is_active = 1);

UPDATE source_availability
SET state = 'reachable', probe = 'local dataset file stat',
    detail = NULL, checked_at = :now
WHERE provider_id IN (SELECT id FROM provider WHERE kind = 'geo_asn' AND is_active = 1);

-- Every implementation this installation does not run: probed, not running.
UPDATE source_availability
SET state = 'unavailable', probe = 'service status endpoint',
    detail = 'not installed on this firewall', checked_at = :now
WHERE provider_id IN (SELECT id FROM provider WHERE is_active = 0);

COMMIT;
