-- opnview — deterministic seed for the schema checks.
--
-- Pure SQL, generated by recursive common table expressions. No Go code, no
-- external generator, and no address literal: every address is synthesised
-- from a counter at generation time and carries no addressing-plan meaning.
-- Nothing in the schema or in the seven screen queries interprets an address;
-- interface membership is carried by foreign keys, never by an address range.
--
-- Bound parameters, all supplied by the caller. The row counts are parameters
-- precisely so the checks can re-run the whole file against a different number
-- of interfaces, clients and flows and show that nothing assumes the defaults.
--
--   :now          the instant the seed pretends to run, UTC epoch seconds
--   :interfaces     how many interfaces to discover        (must be >= 2)
--   :clients      how many clients to observe          (must be > :interfaces)
--   :rules        how many firewall rules to discover  (must be >= 2)
--   :owners       how many owners the user has created (must be >= 1)
--   :flow_rows    rows in flow, the largest growing table
--   :alerts       rows in security_event
--   :pair_rows    logical pairs in pair_volume_observation; each one is
--                 offered twice, once per direction, and must collapse to one
--   :ipv6_every   every Nth slot of the address pool below is IPv6 rather than
--                 IPv4 (must be >= 2). It is a PARAMETER and not a proportion
--                 written into this file, for the same reason the counts are:
--                 the checks re-run the whole seed with a different value, so
--                 nothing may assume how much of a network is v6 -- and because
--                 it changes which FAMILY a row carries and never HOW MANY rows
--                 exist, the row counts and their determinism comparisons stay
--                 legible against the counts above.
--
-- Running the file twice against the same fresh database produces identical
-- row counts per table.

PRAGMA foreign_keys = ON;

BEGIN IMMEDIATE;

-- ---------------------------------------------------------------------------
-- The address pool: one row per numbered slot, carrying that slot's address in
-- both families.
--
-- WHY BOTH FAMILIES PER SLOT rather than one family per slot: a filter-log
-- record reports a single ipversion, so both of its endpoints are of one family.
-- Holding both addresses for every slot lets a generated flow pick its family
-- and then take both endpoints from that family, which is what a real record
-- looks like. A client, meanwhile, carries ONE last_address, and a dual-stack
-- machine really does appear in flows of both families -- so the client's own
-- family and its flows' families are decided separately and deliberately.
--
-- NEITHER ADDRESS IS A LITERAL. Both are synthesised from the slot number, and
-- neither carries any addressing-plan meaning: nothing in the schema or in the
-- seven screen queries interprets an address, and interface membership is
-- carried by foreign keys. The IPv6 form is eight hexadecimal groups derived
-- from the slot, deliberately NOT a documentation prefix, because a recognisable
-- prefix would be a literal about somebody's addressing.
--
-- It is a TEMP table, so it lives for this connection only and appears in no
-- entity list: it is a generator, not part of the model.
-- ---------------------------------------------------------------------------
CREATE TEMP TABLE synth_address (
    slot       INTEGER PRIMARY KEY,
    address_v4 TEXT NOT NULL,
    address_v6 TEXT NOT NULL
);

WITH RECURSIVE local_slot (slot) AS (
    SELECT 1
    UNION ALL
    SELECT slot + 1 FROM local_slot WHERE slot < :clients + 3
),
external_slot (slot) AS (
    SELECT 1000000
    UNION ALL
    SELECT slot + 1 FROM external_slot
    WHERE slot < 1000000 + max(3999, :pair_rows)
),
every_slot (slot) AS (
    SELECT slot FROM local_slot
    UNION
    SELECT slot FROM external_slot
)
INSERT INTO synth_address (slot, address_v4, address_v6)
SELECT
    slot,
    printf('%d.%d.%d.%d',
           (slot / 16777216) % 256, (slot / 65536) % 256, (slot / 256) % 256, slot % 256),
    printf('%x:%x:%x:%x:%x:%x:%x:%x',
           (slot * 7) % 65536, (slot * 11) % 65536, (slot * 13) % 65536,
           (slot * 17) % 65536, (slot * 19) % 65536, (slot * 23) % 65536,
           (slot * 29) % 65536, slot % 65536)
FROM every_slot;

-- ---------------------------------------------------------------------------
-- The provider registry already holds one row per surveyed implementation, with
-- none active. A probe round has now run, so the seed marks the providers this
-- pretend-installation reads.
--
-- ONE PER EXCLUSIVE KIND, AND THAT IS THE RULE RATHER THAN A HABIT. The partial
-- unique index rejects a second active provider of a kind whose destination rows
-- do not carry their provider; it deliberately does not govern security_event,
-- dhcp_lease, measurement_sample or reconciled_state, where two active providers
-- are two attributed sets of rows rather than one doubled figure.
--
-- THIS INSTALLATION RUNS TWO DHCP SERVERS, because that is the deployment the
-- concurrency was decided for: one issuing on one VLAN and another on a second,
-- two scopes with no overlap. Both are active, both contribute leases below, and
-- one machine is leased by both -- which is ONE client holding TWO leases, because
-- the identity cascade keys on the DHCP client identifier and then on the MAC,
-- neither of them scoped to an interface. The concurrent security_event case is
-- exercised where a second implementation is registered, further down in
-- sql/schema-checks.sh.
--
-- flow_volume is NOT activated, and that is the ruling rather than an omission:
-- pair_volume_observation is derived from flow by step 5, so nothing collects
-- that kind and nothing probes it. Its rows below are seeded directly, as the
-- derivation would write them.
--
-- Everything below that needs a provider looks it up by kind and activeness,
-- never by name, with ONE deliberate exception: the lease blocks name the two DHCP
-- servers by key, because the whole point of this installation is that two of them
-- are running and every lease row has to say which one issued it. Naming them is
-- what the fixture is FOR; nothing in the schema, in a query or in an index tests
-- those strings.
-- ---------------------------------------------------------------------------
-- A source of the reconciled_state kind. The schema registers none -- a registry
-- row is a claim that an implementation exists, and no connector for a
-- state-shaped source is written yet -- so this pretend-installation registers
-- the one it pretends to run, which is the INSERT such a connector's cycle would
-- add. The name is an example value in a fixture and matches no product.
INSERT INTO provider (kind, provider_key, display_name, is_active, registered_at)
VALUES ('reconciled_state', 'example-state-source', 'Example state source', 0, :now)
ON CONFLICT (kind, provider_key) DO NOTHING;

INSERT INTO source_availability (provider_id, state, probe, detail, checked_at)
SELECT p.id, 'unavailable', 'not_yet_probed', NULL, 0
FROM provider AS p
WHERE NOT EXISTS (SELECT 1 FROM source_availability a WHERE a.provider_id = p.id);

UPDATE provider SET is_active = 1
WHERE (kind, provider_key) IN (
    VALUES ('firewall_log', 'pf'),
           ('security_event', 'suricata'),
           ('measurement_sample', 'insight'),
           ('dhcp_lease', 'kea'),
           ('dhcp_lease', 'dnsmasq'),
           ('dns_lookup', 'unbound'),
           ('geo_asn', 'maxmind_geolite2'),
           ('reconciled_state', 'example-state-source')
);

-- ---------------------------------------------------------------------------
-- Interfaces. The last one is discovered as a tunnel, every other as a VLAN, so
-- both kinds are present whatever :interfaces is. link_kind is derived from the
-- discovered link type and from nothing else: no name is inspected anywhere.
-- ---------------------------------------------------------------------------
WITH RECURSIVE counter (n) AS (
    SELECT 1
    UNION ALL
    SELECT n + 1 FROM counter WHERE n < :interfaces
),
discovered AS (
    SELECT
        n,
        CASE WHEN n = :interfaces THEN 'tunnel' ELSE 'vlan' END AS link_type
    FROM counter
)
INSERT INTO interface (id, identifier, device, description,
                     user_label, status, enabled, link_type, link_kind, vlan_tag,
                     address_family, first_seen_at, last_seen_at)
SELECT
    n,
    printf('interface-identifier-%d', n),
    printf('device-%d', n),
    printf('discovered-description-%d', n),
    NULL,
    -- The link and administrative states, verbatim as the API reports them.
    -- Synthesised tokens, for the reason the descriptions above are: the
    -- survey establishes the two fields and not their encoding, so a token
    -- shaped like an OPNsense value would be asserting one. What the seed has
    -- to exercise is that an interface can carry a state other than the
    -- common one, and that an interface discovered without one reads as not
    -- reported rather than as switched off.
    CASE WHEN n % 5 = 0 THEN NULL
         WHEN n % 3 = 0 THEN 'link-state-alternative'
         ELSE 'link-state-primary' END,
    CASE WHEN n % 5 = 0 THEN NULL
         WHEN n % 4 = 0 THEN 'admin-state-alternative'
         ELSE 'admin-state-primary' END,
    link_type,
    CASE link_type
        WHEN 'tunnel' THEN 'tunnel'
        WHEN 'vlan' THEN 'vlan'
        ELSE 'other'
    END,
    100 + n,
    4,
    :now - 8640000,
    :now
FROM discovered;

-- The interface map covers every discovered interface. Flows carrying a raw
-- device name absent from this table exercise the "not found" state.
INSERT INTO interface_map (device, description, interface_id, discovered_at)
SELECT device, description, id, :now - 8640000 FROM interface;

-- ---------------------------------------------------------------------------
-- Firewall rules.
-- ---------------------------------------------------------------------------
WITH RECURSIVE counter (n) AS (
    SELECT 1
    UNION ALL
    SELECT n + 1 FROM counter WHERE n < :rules
)
INSERT INTO rule (id, pf_label, description, action, direction, logs_matches,
                  is_automatic, discovered_at)
SELECT
    n,
    printf('rule-label-%d', n),
    printf('rule-description-%d', n),
    CASE WHEN n % 4 = 0 THEN 'block' ELSE 'pass' END,
    CASE WHEN n % 2 = 0 THEN 'in' ELSE 'out' END,
    -- All three states of the logging flag, because all three occur: a rule
    -- that logs, a rule that does not -- whose traffic opnview can never see,
    -- the second observation-point limit -- and a rule discovered from a
    -- source that did not report the flag at all.
    CASE WHEN n % 7 = 0 THEN 0 WHEN n % 11 = 0 THEN NULL ELSE 1 END,
    CASE WHEN n % 9 = 0 THEN 1 ELSE 0 END,
    :now - 8640000
FROM counter;

-- ---------------------------------------------------------------------------
-- Owners. A row per person the user told opnview about. The firewall knows
-- nothing about any of them: ownership is entered in opnview and never
-- inferred, so these rows stand for user input and for nothing observed.
-- ---------------------------------------------------------------------------
WITH RECURSIVE counter (n) AS (
    SELECT 1
    UNION ALL
    SELECT n + 1 FROM counter WHERE n < :owners
)
INSERT INTO owner (id, display_name, created_at, updated_at)
SELECT n, printf('owner-name-%d', n), :now - 8640000, :now - 86400
FROM counter;

-- ---------------------------------------------------------------------------
-- Clients.
--
-- The first octet of the MAC is 0x10 plus twice a counter modulo 8, so the
-- second hex digit walks 0, 2, 4, 6, 8, a, c, e. Four of those carry the IEEE
-- locally-administered bit (2, 6, a, e) and are randomised identities; the
-- other four (0, 4, 8, c) are globally administered burned-in addresses and
-- must NOT be marked unstable. Both halves are therefore present in every run.
--
-- Every tenth client has no MAC at all: the filter log carries none, so a
-- client seen only in flows must still be representable. Its identity falls to
-- the last level of the cascade, the address behind its interface over a
-- validity interval.
-- ---------------------------------------------------------------------------
WITH RECURSIVE counter (n) AS (
    SELECT 1
    UNION ALL
    SELECT n + 1 FROM counter WHERE n < :clients
),
generated AS (
    SELECT
        n,
        ((n - 1) % :interfaces) + 1 AS interface_id,
        CASE
            WHEN n % 10 = 0 THEN NULL
            ELSE printf('%02x:%02x:%02x:%02x:%02x:%02x',
                        16 + (((n - 1) % 8) * 2),
                        (n * 7) % 256, (n * 13) % 256,
                        (n * 29) % 256, (n * 37) % 256, n % 256)
        END AS mac,
        -- The client's own family. It is keyed on the client's POSITION WITHIN
        -- ITS INTERFACE rather than on its id, so every interface holds at least
        -- one IPv6 client whatever the interface count is -- an id-keyed rule
        -- aliases with the interface stride and can leave a whole interface
        -- single-family, which would make a per-interface screen untestable for
        -- one of the two.
        CASE WHEN ((n - 1) / :interfaces) % :ipv6_every = 0
             THEN a.address_v6 ELSE a.address_v4 END AS address
    FROM counter
    JOIN synth_address AS a ON a.slot = n
)
INSERT INTO client (id, identity_kind, identity_key, interface_id, mac, hostname,
                    vendor_hint, last_address, first_seen_at, last_seen_at)
SELECT
    n,
    CASE
        WHEN mac IS NULL THEN 'address_in_interface'
        WHEN n % 3 = 1 THEN 'dhcp_client_id'
        ELSE 'mac'
    END,
    CASE
        WHEN mac IS NULL THEN printf('%d|%s|%d', interface_id, address, :now - 8640000)
        WHEN n % 3 = 1 THEN printf('client-identity-%d', n)
        ELSE mac
    END,
    interface_id,
    mac,
    CASE WHEN mac IS NULL THEN NULL ELSE printf('host-%d', n) END,
    printf('vendor-hint-%d', n % 17),
    address,
    :now - 8640000,
    :now
FROM generated;

-- One address, reissued to a different machine after the first lease expired.
-- The two observations must stay two clients: the address level of the cascade
-- keys on the lease validity start, so the reissue produces a different
-- identity_key and nothing merges.
WITH reissued AS (
    SELECT printf('%d.%d.%d.%d',
                  ((:clients + 1) / 16777216) % 256, ((:clients + 1) / 65536) % 256,
                  ((:clients + 1) / 256) % 256, (:clients + 1) % 256) AS address
)
INSERT INTO client (id, identity_kind, identity_key, interface_id, mac, hostname,
                    vendor_hint, last_address, first_seen_at, last_seen_at)
SELECT :clients + 1, 'address_in_interface',
       printf('%d|%s|%d', 1, address, :now - 17280000),
       1, NULL, NULL, NULL, address, :now - 17280000, :now - 16416000
FROM reissued
UNION ALL
SELECT :clients + 2, 'address_in_interface',
       printf('%d|%s|%d', 1, address, :now - 2592000),
       1, NULL, NULL, NULL, address, :now - 2592000, :now
FROM reissued;

-- The user has attributed every third client to an owner, and has left the
-- rest unattributed, which is the normal state of a network: ownership is
-- assigned by hand and is never derived from a hostname, a MAC prefix or a
-- vendor hint. Each owner ends up holding several machines, so the per-person
-- view has something to aggregate, and the majority of clients stay in the
-- unassigned bucket the diagnostic query has to keep visible.
--
-- The reissued pair above is deliberately left unowned: it exists to show two
-- identities behind one address, and attributing it would blur that.
UPDATE client
SET owner_id = (((id / 3) - 1) % :owners) + 1,
    owner_assigned_at = :now - 86400
WHERE id % 3 = 0 AND id <= :clients;

-- ---------------------------------------------------------------------------
-- DHCP leases. One per client that has a MAC, spread back over five months so
-- that a finite retention horizon has something to purge, plus the two leases
-- of the reissued address above.
--
-- BOTH BACKEND BEHAVIOURS APPEAR, because the model now distinguishes them. A
-- Kea lease carries a REAL validity start, `expire` minus `valid_lifetime`, and
-- its generation key rests on that start. A Dnsmasq lease carries NO start at
-- all -- the backend reports none, so the column is NULL rather than holding a
-- substitute -- and its generation key rests on the expiry, which is what keeps a
-- re-poll from inserting a second row. A standing reservation reports neither and
-- is keyed on the day it was observed.
-- ---------------------------------------------------------------------------
INSERT INTO dhcp_lease (provider_id, client_id, backend, address, mac, hostname,
                        dhcp_client_id, duid, iaid,
                        vendor_hint, lease_state, interface_id, starts_at, generation_key,
                        expires_at, observed_at)
SELECT
    (SELECT id FROM provider WHERE kind = 'dhcp_lease' AND provider_key = 'kea'),
    id,
    'kea',
    last_address,
    mac,
    hostname,
    CASE WHEN identity_kind = 'dhcp_client_id' THEN identity_key END,
    NULL,
    NULL,
    vendor_hint,
    'active',
    interface_id,
    :now - ((id % 8) * 1728000) - 3600,
    'start:' || (:now - ((id % 8) * 1728000) - 3600),
    :now - ((id % 8) * 1728000) + 86400,
    :now - ((id % 8) * 1728000)
FROM client
WHERE mac IS NOT NULL;

INSERT INTO dhcp_lease (provider_id, client_id, backend, address, mac, hostname,
                        dhcp_client_id, duid, iaid,
                        vendor_hint, lease_state, interface_id, starts_at, generation_key,
                        expires_at, observed_at)
SELECT (SELECT id FROM provider WHERE kind = 'dhcp_lease' AND provider_key = 'kea'), id, 'kea', last_address, NULL, NULL, NULL, NULL, NULL, NULL,
       'expired', interface_id, :now - 17280000, 'start:' || (:now - 17280000),
       :now - 16416000, :now - 16416000
FROM client WHERE id = :clients + 1
UNION ALL
SELECT (SELECT id FROM provider WHERE kind = 'dhcp_lease' AND provider_key = 'kea'), id, 'kea', last_address, NULL, NULL, NULL, NULL, NULL, NULL,
       'active', interface_id, :now - 2592000, 'start:' || (:now - 2592000),
       :now + 86400, :now
FROM client WHERE id = :clients + 2;

-- The Dnsmasq half: a backend that reports no validity start. Every one of these
-- rows carries a NULL start and a generation key resting on the expiry, and the
-- last one is a standing reservation, which reports neither and is keyed on the
-- day it was seen. They are spread over the same five months so the purge has
-- both something to remove and something to leave alone.
INSERT INTO dhcp_lease (provider_id, client_id, backend, address, mac, hostname,
                        dhcp_client_id, duid, iaid,
                        vendor_hint, lease_state, interface_id, starts_at, generation_key,
                        expires_at, observed_at)
SELECT
    (SELECT id FROM provider WHERE kind = 'dhcp_lease' AND provider_key = 'dnsmasq'),
    id,
    'dnsmasq',
    last_address,
    mac,
    hostname,
    NULL,
    NULL,
    NULL,
    vendor_hint,
    'active',
    interface_id,
    NULL,
    'expiry:' || (:now - ((id % 8) * 1728000) + 43200),
    :now - ((id % 8) * 1728000) + 43200,
    :now - ((id % 8) * 1728000)
FROM client
WHERE mac IS NOT NULL AND id % 4 = 0
UNION ALL
SELECT
    (SELECT id FROM provider WHERE kind = 'dhcp_lease' AND provider_key = 'dnsmasq'),
    id,
    'dnsmasq',
    last_address,
    mac,
    hostname,
    NULL,
    NULL,
    NULL,
    vendor_hint,
    'reserved',
    interface_id,
    NULL,
    'observed_day:' || ((:now - ((id % 8) * 1728000)) / 86400 * 86400),
    NULL,
    :now - ((id % 8) * 1728000)
FROM client
WHERE mac IS NOT NULL AND id % 7 = 0;

-- ---------------------------------------------------------------------------
-- ONE MACHINE, TWO SERVERS, TWO VLANs. This is the deployment the dhcp_lease
-- kind was made concurrent for, and it is seeded explicitly rather than left to
-- fall out of the blocks above, because it is the claim the decision rests on.
--
-- The client below already holds a lease from the first server, on the interface
-- it was discovered behind. This adds a lease from the SECOND server, at a
-- different address, on a DIFFERENT interface. It is ONE client row with TWO
-- leases, and that is the truth rather than a collapse: the identity cascade keys
-- on the DHCP client identifier and then on the MAC, neither of them scoped to an
-- interface, so the same machine reported by two servers is the same machine.
--
-- The second interface is derived arithmetically from the first, so nothing here
-- assumes how many interfaces exist or which one anything sits behind; the
-- expression cannot yield the interface the client is already on.
-- ---------------------------------------------------------------------------
INSERT INTO dhcp_lease (provider_id, client_id, backend, address, mac, hostname,
                        dhcp_client_id, duid, iaid,
                        vendor_hint, lease_state, interface_id, starts_at, generation_key,
                        expires_at, observed_at)
SELECT
    (SELECT id FROM provider WHERE kind = 'dhcp_lease' AND provider_key = 'dnsmasq'),
    c.id,
    'dnsmasq',
    a.address_v4,
    c.mac,
    c.hostname,
    NULL,
    NULL,
    NULL,
    c.vendor_hint,
    'active',
    1 + (c.interface_id % :interfaces),
    NULL,
    'expiry:' || (:now + 43200),
    :now + 43200,
    :now
FROM client AS c
JOIN synth_address AS a ON a.slot = :clients + 3
WHERE c.mac IS NOT NULL
  AND c.interface_id IS NOT NULL
  AND c.id = (SELECT min(id) FROM client
              WHERE mac IS NOT NULL AND interface_id IS NOT NULL);

-- ---------------------------------------------------------------------------
-- Flows — the largest growing table, one row per filter-log record.
--
-- Timestamps walk backwards from :now in 97-second steps, so the seeded
-- history is deterministic, dense near the present and long enough for a
-- 90-day retention horizon to bite.
--
-- Shape of the generated population:
--   i % 3 = 0   east-west: both endpoints sit in a discovered interface
--   i % 3 <> 0  north-south: the destination is outside every interface
--   i % 3 = 2   the flow will also carry a site-name attribution
--   i % 7 = 0   blocked
--   i % 11 = 0  the rid matches no known rule  -> rule_lookup_state not_found
--   i % 13 = 0  the raw device name is absent from the interface map
-- The moduli are coprime with :clients in the default run, so every client
-- sees flows of every kind rather than one kind only.
-- ---------------------------------------------------------------------------
WITH RECURSIVE counter (i) AS (
    SELECT 1
    UNION ALL
    SELECT i + 1 FROM counter WHERE i < :flow_rows
),
chosen AS (
    SELECT
        i,
        :now - (i * 97)                                      AS observed_at,
        ((i - 1) % :clients) + 1                             AS src_client_id,
        CASE WHEN i % 3 = 0 THEN (i % :clients) + 1 END      AS dst_client_id,
        i % 7 = 0                                            AS is_blocked,
        i % 11 = 0                                           AS rule_missing,
        i % 13 = 0                                           AS interface_missing,
        -- The record's address family. A filter-log record reports ONE
        -- ipversion, so both endpoints below are taken from the same family.
        i % :ipv6_every = 0                                  AS is_ipv6,
        CASE WHEN i % 3 = 0 THEN (i % :clients) + 1
             ELSE 1000000 + (i % 4000) END                   AS dst_slot
    FROM counter
),
placed AS (
    SELECT
        i, observed_at, src_client_id, dst_client_id,
        is_blocked, rule_missing, interface_missing, is_ipv6,
        ((src_client_id - 1) % :interfaces) + 1 AS src_interface_id,
        CASE WHEN dst_client_id IS NOT NULL
             THEN ((dst_client_id - 1) % :interfaces) + 1 END AS dst_interface_id,
        CASE WHEN is_ipv6 THEN src.address_v6 ELSE src.address_v4 END AS src_address,
        CASE WHEN is_ipv6 THEN dst.address_v6 ELSE dst.address_v4 END AS dst_address
    FROM chosen
    JOIN synth_address AS src ON src.slot = src_client_id
    JOIN synth_address AS dst ON dst.slot = dst_slot
)
INSERT INTO flow (id, log_digest, observed_at, ingested_at, interface_device,
                  interface_lookup_state, src_interface_id, dst_interface_id,
                  src_client_id, dst_client_id, src_address, dst_address,
                  src_port, dst_port, protocol, ip_version, action, direction,
                  log_reason, packet_bytes, rid, rule_id, rule_lookup_state,
                  traffic_scope)
SELECT
    i,
    printf('log-digest-%d', i),
    observed_at,
    observed_at + 5,
    CASE WHEN interface_missing
         THEN printf('unmapped-device-%d', i)
         ELSE printf('device-%d', src_interface_id) END,
    CASE WHEN interface_missing THEN 'not_found' ELSE 'resolved' END,
    src_interface_id,
    dst_interface_id,
    src_client_id,
    dst_client_id,
    src_address,
    dst_address,
    1024 + ((i * 17) % 64000),
    1 + ((i * 13) % 65000),
    CASE WHEN i % 2 = 0 THEN 'tcp' ELSE 'udp' END,
    -- The family the filter log reported. It is the only column from which a
    -- v4-against-v6 split is answerable: an address column alone cannot be
    -- classified, and the project forbids inferring an addressing plan.
    CASE WHEN is_ipv6 THEN 6 ELSE 4 END,
    CASE WHEN is_blocked THEN 'block' ELSE 'pass' END,
    CASE WHEN i % 2 = 0 THEN 'in' ELSE 'out' END,
    -- The reason the record was logged. The survey establishes the field and
    -- not its value set, so these tokens are synthesised here exactly as the
    -- labels and descriptions above are, rather than asserting a vocabulary
    -- OPNsense has not published. What the seed has to exercise is that two
    -- distinct reasons are representable and queryable, and that a record
    -- whose reason is not the common one is not thereby a rule denial.
    CASE WHEN i % 11 = 0 THEN 'log-reason-alternative' ELSE 'log-reason-primary' END,
    40 + ((i * 37) % 1460),
    CASE WHEN rule_missing
         THEN printf('orphan-rule-label-%d', i)
         ELSE printf('rule-label-%d', ((i - 1) % :rules) + 1) END,
    CASE WHEN rule_missing THEN NULL ELSE ((i - 1) % :rules) + 1 END,
    CASE WHEN rule_missing THEN 'not_found' ELSE 'resolved' END,
    -- Interface membership and nothing else. The CHECK on the column rejects any
    -- other value, so this expression cannot drift from the schema's.
    CASE WHEN src_interface_id IS NOT NULL AND dst_interface_id IS NOT NULL
         THEN 'east_west' ELSE 'north_south' END
FROM placed;

-- ---------------------------------------------------------------------------
-- Resolver lookups, and the site names inferred from them.
--
-- Only the north-south flows with i % 3 = 2 get an attribution, so every
-- client also has unattributed flows: the Client screen must return those with
-- their address, country and operator and a null site name rather than
-- dropping them, and the attribution rate must be below 100 per cent.
-- ---------------------------------------------------------------------------
INSERT INTO dns_resolution (id, lookup_key, client_address, client_id, domain,
                            resolver, action, answer_source, rcode,
                            dnssec_status, looked_up_at, ingested_at)
SELECT
    id,
    printf('lookup-uuid-%d', id),
    src_address,
    src_client_id,
    printf('name-%d.example-zone-%d.invalid', id % 997, id % 13),
    'unbound',
    'pass',
    CASE WHEN id % 5 = 0 THEN 'cache' ELSE 'recursion' END,
    'NOERROR',
    -- The validation verdict. Synthesised, for the reason the flow reasons
    -- above are: the survey establishes the field and not its value set. One
    -- lookup in nine carries no verdict at all, which is "not reported" and
    -- not "unvalidated" -- the distinction the nullable column exists for.
    CASE WHEN id % 7 = 3 THEN NULL
         ELSE printf('dnssec-status-%d', id % 3) END,
    observed_at - (1 + (id % 30)),
    observed_at
FROM flow
WHERE id % 3 = 2;

INSERT INTO domain_attribution (flow_id, dns_resolution_id, site_name,
                                correlation_delay_seconds, attributed_at)
SELECT id, id, printf('name-%d.example-zone-%d.invalid', id % 997, id % 13),
       1 + (id % 30), observed_at
FROM flow
WHERE id % 3 = 2;

-- ---------------------------------------------------------------------------
-- The blocklists the resolver refused lookups against.
--
-- The NAME is observed: the endpoint returns it verbatim on every row. The
-- PURPOSE is user input, so three of the four are classified and the fourth is
-- left alone -- the normal state, and the one the "purpose not assigned"
-- rendering exists for. Nothing derives a purpose from a name here or
-- anywhere else; the names below are synthesised from a counter and carry no
-- meaning a machine could read.
-- ---------------------------------------------------------------------------
WITH RECURSIVE counter (n) AS (
    SELECT 1
    UNION ALL
    SELECT n + 1 FROM counter WHERE n < 4
)
INSERT INTO blocklist (id, name, purpose, purpose_assigned_at, first_seen_at, last_seen_at)
SELECT
    n,
    printf('example-blocklist-%d', n),
    CASE n WHEN 1 THEN 'advertising' WHEN 2 THEN 'threat' WHEN 3 THEN 'tracking' END,
    CASE WHEN n <= 3 THEN :now - 86400 END,
    :now - 2592000,
    :now
FROM counter;

-- Blocked lookups, which the pass-only rows above do not exercise.
--
-- Four fifths name the list that refused them and one fifth does not: the
-- endpoint does not attribute every block, and "blocked, list not recorded" is
-- a modelled state rather than a silent merge into a bucket. Every one of the
-- four lists is used, the unclassified one included, so a query grouping by
-- purpose has an unassigned group to return.
--
-- These rows carry no attribution, deliberately: a blocked lookup produces no
-- flow, so there is nothing to attribute and nothing to correlate.
WITH RECURSIVE counter (n) AS (
    SELECT 1
    UNION ALL
    SELECT n + 1 FROM counter WHERE n < 400
)
INSERT INTO dns_resolution (id, lookup_key, client_address, client_id, domain,
                            resolver, action, answer_source, rcode, dnssec_status,
                            blocklist_id, looked_up_at, ingested_at)
SELECT
    1000000000 + n,
    printf('blocked-lookup-uuid-%d', n),
    c.last_address,
    c.id,
    printf('blocked-name-%d.example-zone-%d.invalid', n % 211, n % 7),
    'unbound',
    CASE WHEN n % 8 = 0 THEN 'drop' ELSE 'block' END,
    'local-data',
    'NXDOMAIN',
    CASE WHEN n % 6 = 0 THEN NULL ELSE printf('dnssec-status-%d', n % 3) END,
    CASE WHEN n % 5 = 0 THEN NULL ELSE ((n - 1) % 4) + 1 END,
    :now - ((n * 97) % 86400),
    :now
FROM counter
JOIN client AS c ON c.id = ((n - 1) % :clients) + 1;

-- ---------------------------------------------------------------------------
-- Geo / ASN cache, one row per synthesised external address. Roughly one in
-- thirty-seven is a modelled cache miss rather than an absent row, so the Map
-- and Client screens can show that the enrichment did not answer instead of
-- silently dropping the volume.
-- ---------------------------------------------------------------------------
-- Every external slot is enriched in BOTH families, because a flow of either
-- family can name it and the Map and Client screens join geo_asn on the address
-- the flow actually carried. Enriching one family only would make every IPv6
-- destination a cache miss, which would look like a dataset problem rather than
-- a seed that had not been extended.
WITH RECURSIVE counter (j) AS (
    SELECT 0
    UNION ALL
    SELECT j + 1 FROM counter WHERE j < max(3999, :pair_rows)
),
generated AS (
    SELECT
        j,
        family,
        CASE WHEN family = 6 THEN a.address_v6 ELSE a.address_v4 END AS address,
        char(65 + (j % 26), 65 + ((j / 26) % 26)) AS country_code,
        j % 37 = 0 AS is_miss
    FROM counter
    JOIN synth_address AS a ON a.slot = 1000000 + j
    CROSS JOIN (SELECT 4 AS family UNION ALL SELECT 6) AS families
)
INSERT INTO geo_asn (address, provider_id, lookup_state, country_code, country_name,
                     latitude, longitude, asn, operator, dataset_build_at, looked_up_at)
SELECT
    address,
    (SELECT id FROM provider WHERE kind = 'geo_asn' AND is_active = 1),
    CASE WHEN is_miss THEN 'miss' ELSE 'resolved' END,
    CASE WHEN is_miss THEN NULL ELSE country_code END,
    CASE WHEN is_miss THEN NULL ELSE printf('country-name-%s', country_code) END,
    CASE WHEN is_miss THEN NULL ELSE ((j % 180) - 90) * 1.0 END,
    CASE WHEN is_miss THEN NULL ELSE ((j % 360) - 180) * 1.0 END,
    CASE WHEN is_miss THEN NULL ELSE 1000 + j END,
    CASE WHEN is_miss THEN NULL ELSE printf('operator-%d', j % 97) END,
    CASE WHEN is_miss THEN NULL ELSE :now - 604800 END,
    :now - ((j % 100) * 86400)
FROM generated;

-- ---------------------------------------------------------------------------
-- Security events, and the per-provider rule-info cache that gives them a
-- severity.
--
-- Every event is attributed to the active provider of the security_event kind
-- and carries the key that provider guarantees stable -- for this one, the eve
-- file id and the byte offset inside it, composed into a single text key by
-- the collector. The ingestion coordinate is not stored as columns here; that
-- is eve_ingest_cursor's concern.
--
-- Rule identities are text. Forty-nine of the fifty are numeric strings and
-- one is deliberately NON-NUMERIC, so a provider whose rules are named rather
-- than numbered is exercised. Ten of the numeric ones are absent from the
-- cache, so the Alerts screen has to render an explicit unknown severity.
--
-- normalised_severity is NULL on every row: Suricata ships no severity inside
-- the event (survey, gap 3), and this restructuring changes nothing about it.
-- ---------------------------------------------------------------------------
WITH RECURSIVE counter (m) AS (
    SELECT 1
    UNION ALL
    SELECT m + 1 FROM counter WHERE m < :alerts
),
generated AS (
    SELECT
        m,
        -- Dense over the last few days, then stretched back over four months,
        -- so the recent window is busy enough to exercise the Alerts screen
        -- and a finite retention horizon still has something to purge.
        :now - (m * 601) - (max(m - 250, 0) * 40000) AS occurred_at,
        ((m - 1) % :clients) + 1                     AS src_client_id,
        -- Three rotated files whatever :alerts is, so the ingestion cursor
        -- always has a watermark per file to record.
        1 + (((m - 1) * 3) / :alerts)                AS file_number,
        m * 4096                                     AS byte_position,
        m % :ipv6_every = 0                          AS is_ipv6
    FROM counter
)
INSERT INTO security_event (id, provider_id, provider_event_key, occurred_at, ingested_at,
                            rule_identity, signature, event_action, normalised_severity,
                            src_address, src_port, dst_address, dst_port, protocol,
                            in_interface_device, src_client_id, src_interface_id, flow_ref)
SELECT
    m,
    (SELECT id FROM provider WHERE kind = 'security_event' AND is_active = 1),
    printf('eve-file-%d:%d', file_number, byte_position),
    occurred_at,
    occurred_at + 30,
    CASE WHEN m % 50 = 3
         THEN 'named-rule-identity-alpha'
         ELSE printf('%d', 1000000 + (m % 50)) END,
    printf('signature-text-%d', m % 50),
    CASE WHEN m % 4 = 0 THEN 'blocked' ELSE 'allowed' END,
    NULL,
    (SELECT CASE WHEN g.is_ipv6 THEN a.address_v6 ELSE a.address_v4 END
     FROM synth_address AS a WHERE a.slot = g.src_client_id),
    1024 + ((m * 19) % 64000),
    (SELECT CASE WHEN g.is_ipv6 THEN a.address_v6 ELSE a.address_v4 END
     FROM synth_address AS a WHERE a.slot = 1000000 + (m % 4000)),
    1 + ((m * 7) % 65000),
    CASE WHEN m % 2 = 0 THEN 'tcp' ELSE 'udp' END,
    printf('device-%d', ((src_client_id - 1) % :interfaces) + 1),
    src_client_id,
    ((src_client_id - 1) % :interfaces) + 1,
    NULL
FROM generated AS g;

-- The cache. normalised_severity is opnview's ordered vocabulary;
-- provider_severity keeps the raw numeric string the provider reported, so the
-- normalisation stays auditable. The mapping 1..4 -> critical, high, medium,
-- low is documented in docs/data-model.md.
WITH RECURSIVE counter (x) AS (
    SELECT 0
    UNION ALL
    SELECT x + 1 FROM counter WHERE x < 39
),
raw AS (
    SELECT x, 1 + (x % 4) AS provider_severity FROM counter
)
INSERT INTO provider_rule_info (provider_id, rule_identity, normalised_severity,
                                provider_severity, category, rule_source, fetched_at)
SELECT
    (SELECT id FROM provider WHERE kind = 'security_event' AND is_active = 1),
    CASE WHEN x = 3 THEN 'named-rule-identity-alpha' ELSE printf('%d', 1000000 + x) END,
    CASE provider_severity
        WHEN 1 THEN 'critical'
        WHEN 2 THEN 'high'
        WHEN 3 THEN 'medium'
        ELSE 'low'
    END,
    printf('%d', provider_severity),
    printf('category-%d', x % 7),
    printf('rule-source-%d', x % 3),
    :now - 3600
FROM raw;

-- ---------------------------------------------------------------------------
-- eve.json ingestion cursor: one watermark per rotated file, with the rotation
-- state. 'lost' is the case where rotation discarded the file the watermark
-- referred to, so the gap is permanent and recorded as such.
--
-- This is a DIFFERENT guarantee from the one on security_event. The unique key
-- here answers "where did the reader stop in this file"; the unique key there
-- answers "have I already stored this event". Merging them would lose one of
-- the two.
-- ---------------------------------------------------------------------------
WITH RECURSIVE counter (m) AS (
    SELECT 1
    UNION ALL
    SELECT m + 1 FROM counter WHERE m < :alerts
),
watermarks AS (
    SELECT 1 + (((m - 1) * 3) / :alerts) AS file_number, m * 4096 AS byte_position
    FROM counter
)
INSERT INTO eve_ingest_cursor (file_id, byte_offset, file_sequence, rotation_state, observed_at)
SELECT 'eve-file-0', 0, 0, 'lost', :now - 604800
UNION ALL
SELECT printf('eve-file-%d', file_number), max(byte_position), file_number,
       CASE WHEN file_number = 3 THEN 'current' ELSE 'rotated' END, :now
FROM watermarks
GROUP BY file_number;

-- ---------------------------------------------------------------------------
-- Daily per-pair volume, DERIVED rather than collected.
--
-- No collector writes this table and none will: the only per-pair endpoint
-- carries neither a port nor a protocol, and `flow` carries both, so these rows
-- are step 5's to compute from `flow`. The seed writes them as that derivation
-- will, which is why this block names no provider.
--
-- The de-duplication it has to respect is unchanged, and the seed still exercises
-- it: a per-pair figure is direction-free, so the seed offers every pair twice
-- with the endpoints swapped and the key collapses them to one logical volume.
-- After this statement the table holds :pair_rows rows, not twice that.
-- ---------------------------------------------------------------------------
WITH RECURSIVE counter (p) AS (
    SELECT 1
    UNION ALL
    SELECT p + 1 FROM counter WHERE p < :pair_rows
),
pairs AS (
    SELECT
        p,
        (((:now / 86400) - (p % 120)) * 86400) AS day_start_at,
        -- The pair's family. Both ends are of one family, as a real conversation
        -- is, and the canonical ordering below is lexicographic over whichever
        -- form that produced.
        CASE WHEN p % :ipv6_every = 0 THEN local.address_v6 ELSE local.address_v4 END
            AS local_address,
        CASE WHEN p % :ipv6_every = 0 THEN peer.address_v6 ELSE peer.address_v4 END
            AS peer_address
    FROM counter
    JOIN synth_address AS local ON local.slot = ((p - 1) % :clients) + 1
    JOIN synth_address AS peer ON peer.slot = 1000000 + p
),
doubled AS (
    SELECT p, day_start_at, local_address AS a, peer_address AS b, 'out' AS observed_direction
    FROM pairs
    UNION ALL
    SELECT p, day_start_at, peer_address AS a, local_address AS b, 'in' AS observed_direction
    FROM pairs
)
INSERT OR IGNORE INTO pair_volume_observation
    (day_start_at, endpoint_low, endpoint_high, service_port, protocol,
     octets, packets, observed_direction, observed_interface_device,
     last_seen_at, ingested_at)
SELECT
    day_start_at,
    min(a, b),
    max(a, b),
    1 + (p % 1000),
    CASE WHEN p % 2 = 0 THEN 'tcp' ELSE 'udp' END,
    1000.0 + p,
    10.0 + (p % 50),
    observed_direction,
    printf('device-%d', ((p - 1) % :interfaces) + 1),
    day_start_at + 86399,
    :now
FROM doubled
ORDER BY p, observed_direction;

-- ---------------------------------------------------------------------------
-- The four pre-computed aggregates.
--
-- They are computed from opnview's own stored flows, not from any Insight
-- column: per-address-pair volume on the firewall exists only at daily
-- resolution and only for 62 days, and per-source totals at 300 s resolution
-- are kept one hour (survey, data source 3), so the 1 h and 24 h periods can
-- only come from opnview's own history. computed_at is the freshness stamp.
-- ---------------------------------------------------------------------------
INSERT INTO volume_aggregate_1h (period_start_at, period_end_at, src_interface_id,
                                 dst_interface_id, peer_address, traffic_scope,
                                 bytes, allowed_connections, blocked_connections, computed_at)
SELECT
    (observed_at / 3600) * 3600,
    (observed_at / 3600) * 3600 + 3600,
    src_interface_id,
    dst_interface_id,
    CASE WHEN dst_interface_id IS NULL THEN dst_address END,
    traffic_scope,
    sum(packet_bytes),
    sum(CASE WHEN action <> 'block' THEN 1 ELSE 0 END),
    sum(CASE WHEN action = 'block' THEN 1 ELSE 0 END),
    :now
FROM flow
WHERE src_interface_id IS NOT NULL
GROUP BY 1, 2, 3, 4, 5, 6;

INSERT INTO volume_aggregate_24h (period_start_at, period_end_at, src_interface_id,
                                  dst_interface_id, peer_address, traffic_scope,
                                  bytes, allowed_connections, blocked_connections, computed_at)
SELECT
    (observed_at / 86400) * 86400,
    (observed_at / 86400) * 86400 + 86400,
    src_interface_id,
    dst_interface_id,
    CASE WHEN dst_interface_id IS NULL THEN dst_address END,
    traffic_scope,
    sum(packet_bytes),
    sum(CASE WHEN action <> 'block' THEN 1 ELSE 0 END),
    sum(CASE WHEN action = 'block' THEN 1 ELSE 0 END),
    :now
FROM flow
WHERE src_interface_id IS NOT NULL
GROUP BY 1, 2, 3, 4, 5, 6;

INSERT INTO volume_aggregate_7d (period_start_at, period_end_at, src_interface_id,
                                 dst_interface_id, peer_address, traffic_scope,
                                 bytes, allowed_connections, blocked_connections, computed_at)
SELECT
    (observed_at / 604800) * 604800,
    (observed_at / 604800) * 604800 + 604800,
    src_interface_id,
    dst_interface_id,
    CASE WHEN dst_interface_id IS NULL THEN dst_address END,
    traffic_scope,
    sum(packet_bytes),
    sum(CASE WHEN action <> 'block' THEN 1 ELSE 0 END),
    sum(CASE WHEN action = 'block' THEN 1 ELSE 0 END),
    :now
FROM flow
WHERE src_interface_id IS NOT NULL
GROUP BY 1, 2, 3, 4, 5, 6;

INSERT INTO volume_aggregate_30d (period_start_at, period_end_at, src_interface_id,
                                  dst_interface_id, peer_address, traffic_scope,
                                  bytes, allowed_connections, blocked_connections, computed_at)
SELECT
    (observed_at / 2592000) * 2592000,
    (observed_at / 2592000) * 2592000 + 2592000,
    src_interface_id,
    dst_interface_id,
    CASE WHEN dst_interface_id IS NULL THEN dst_address END,
    traffic_scope,
    sum(packet_bytes),
    sum(CASE WHEN action <> 'block' THEN 1 ELSE 0 END),
    sum(CASE WHEN action = 'block' THEN 1 ELSE 0 END),
    :now
FROM flow
WHERE src_interface_id IS NOT NULL
GROUP BY 1, 2, 3, 4, 5, 6;

-- ---------------------------------------------------------------------------
-- The four per-owner aggregates.
--
-- Computed from opnview's own flows joined to client.owner_id, which is the
-- only thing that carries a person: nothing here infers an owner, and the join
-- is from flow so that a flow from an unowned client lands in the NULL slot
-- rather than being dropped. That NULL slot is the unassigned bucket, and it
-- is the majority of the network by design.
--
-- client_count is the distinct clients that contributed to that slot alone. It
-- is not summable across slots and no query below sums it.
-- ---------------------------------------------------------------------------
INSERT INTO owner_volume_aggregate_1h (period_start_at, period_end_at, owner_id,
                                       traffic_scope, bytes, allowed_connections,
                                       blocked_connections, client_count, computed_at)
SELECT
    (f.observed_at / 3600) * 3600,
    (f.observed_at / 3600) * 3600 + 3600,
    c.owner_id,
    f.traffic_scope,
    sum(f.packet_bytes),
    sum(CASE WHEN f.action <> 'block' THEN 1 ELSE 0 END),
    sum(CASE WHEN f.action = 'block' THEN 1 ELSE 0 END),
    count(DISTINCT f.src_client_id),
    :now
FROM flow AS f
JOIN client AS c ON c.id = f.src_client_id
GROUP BY 1, 2, 3, 4;

INSERT INTO owner_volume_aggregate_24h (period_start_at, period_end_at, owner_id,
                                        traffic_scope, bytes, allowed_connections,
                                        blocked_connections, client_count, computed_at)
SELECT
    (f.observed_at / 86400) * 86400,
    (f.observed_at / 86400) * 86400 + 86400,
    c.owner_id,
    f.traffic_scope,
    sum(f.packet_bytes),
    sum(CASE WHEN f.action <> 'block' THEN 1 ELSE 0 END),
    sum(CASE WHEN f.action = 'block' THEN 1 ELSE 0 END),
    count(DISTINCT f.src_client_id),
    :now
FROM flow AS f
JOIN client AS c ON c.id = f.src_client_id
GROUP BY 1, 2, 3, 4;

INSERT INTO owner_volume_aggregate_7d (period_start_at, period_end_at, owner_id,
                                       traffic_scope, bytes, allowed_connections,
                                       blocked_connections, client_count, computed_at)
SELECT
    (f.observed_at / 604800) * 604800,
    (f.observed_at / 604800) * 604800 + 604800,
    c.owner_id,
    f.traffic_scope,
    sum(f.packet_bytes),
    sum(CASE WHEN f.action <> 'block' THEN 1 ELSE 0 END),
    sum(CASE WHEN f.action = 'block' THEN 1 ELSE 0 END),
    count(DISTINCT f.src_client_id),
    :now
FROM flow AS f
JOIN client AS c ON c.id = f.src_client_id
GROUP BY 1, 2, 3, 4;

INSERT INTO owner_volume_aggregate_30d (period_start_at, period_end_at, owner_id,
                                        traffic_scope, bytes, allowed_connections,
                                        blocked_connections, client_count, computed_at)
SELECT
    (f.observed_at / 2592000) * 2592000,
    (f.observed_at / 2592000) * 2592000 + 2592000,
    c.owner_id,
    f.traffic_scope,
    sum(f.packet_bytes),
    sum(CASE WHEN f.action <> 'block' THEN 1 ELSE 0 END),
    sum(CASE WHEN f.action = 'block' THEN 1 ELSE 0 END),
    count(DISTINCT f.src_client_id),
    :now
FROM flow AS f
JOIN client AS c ON c.id = f.src_client_id
GROUP BY 1, 2, 3, 4;

-- ---------------------------------------------------------------------------
-- Provider availability. One row per registry row already exists, created by
-- the schema in the "not yet probed" state; the seed records what a probe round
-- found. Every kind therefore carries both halves of the picture: which
-- implementations are reachable, and which of them are active.
--
-- The active security-event provider is present but disabled and the active
-- DNS-lookup provider is unavailable, so the screens have both degraded states
-- to render while their kinds still have an active provider. The
-- implementations this installation does not run are 'unavailable' -- a
-- modelled state, not an absent row.
-- ---------------------------------------------------------------------------
UPDATE source_availability
SET state = 'reachable', probe = 'GET /api/diagnostics/firewall/log',
    detail = NULL, checked_at = :now
WHERE provider_id IN (SELECT id FROM provider WHERE kind = 'firewall_log' AND is_active = 1);

UPDATE source_availability
SET state = 'present_but_disabled', probe = 'GET /api/ids/service/status',
    detail = 'status reported stopped', checked_at = :now
WHERE provider_id IN (SELECT id FROM provider WHERE kind = 'security_event' AND is_active = 1);

-- The measurement source. Its probe is the firewall's own NetFlow configuration,
-- which is what governs whether the per-pair snapshot it samples holds anything;
-- the probe moved here from the flow_volume row with the sampler, because this is
-- the row whose material it governs.
UPDATE source_availability
SET state = 'reachable', probe = 'GET /api/diagnostics/netflow/is_enabled',
    detail = 'local collection enabled', checked_at = :now
WHERE provider_id IN (SELECT id FROM provider WHERE kind = 'measurement_sample' AND is_active = 1);

UPDATE source_availability
SET state = 'reachable', probe = 'example state source probe',
    detail = NULL, checked_at = :now
WHERE provider_id IN (SELECT id FROM provider WHERE kind = 'reconciled_state' AND is_active = 1);

-- The two DHCP servers, each with ITS OWN probe endpoint. One availability row per
-- server, and neither borrows the other's conclusion: that is what the seam is for,
-- and a single statement covering both active rows would have written the first
-- server's probe onto the second server's row.
UPDATE source_availability
SET state = 'reachable', probe = 'GET /api/kea/service/status',
    detail = NULL, checked_at = :now
WHERE provider_id IN (SELECT id FROM provider
                      WHERE kind = 'dhcp_lease' AND provider_key = 'kea' AND is_active = 1);

UPDATE source_availability
SET state = 'reachable', probe = 'GET /api/dnsmasq/service/status',
    detail = 'serving a range on its own interface', checked_at = :now
WHERE provider_id IN (SELECT id FROM provider
                      WHERE kind = 'dhcp_lease' AND provider_key = 'dnsmasq' AND is_active = 1);

UPDATE source_availability
SET state = 'unavailable', probe = 'GET /api/unbound/overview/is_enabled',
    detail = 'query reporting is off', checked_at = :now
WHERE provider_id IN (SELECT id FROM provider WHERE kind = 'dns_lookup' AND is_active = 1);

UPDATE source_availability
SET state = 'reachable', probe = 'local dataset file stat',
    detail = NULL, checked_at = :now
WHERE provider_id IN (SELECT id FROM provider WHERE kind = 'geo_asn' AND is_active = 1);

-- Every implementation this installation does not run: probed, not running.
UPDATE source_availability
SET state = 'unavailable', probe = 'service status endpoint',
    detail = 'not installed on this firewall', checked_at = :now
WHERE provider_id IN (SELECT id FROM provider WHERE is_active = 0);

-- ---------------------------------------------------------------------------
-- Collection gaps: the intervals opnview knows it did not cover.
--
-- All three reasons are seeded, because all three are measured failure modes
-- rather than hypotheses: the filter log has no server-side cursor, an eve.json
-- rotation can discard a watermarked file, and the resolver query endpoint
-- ignores the window it is given. Some are older than a 90-day horizon so the
-- purge has something to remove, and some are recent so it has something to
-- leave alone.
--
-- A gap is attributed to the provider whose data is missing, looked up by kind
-- and activeness -- never by name.
-- ---------------------------------------------------------------------------
WITH RECURSIVE counter (k) AS (
    SELECT 1
    UNION ALL
    SELECT k + 1 FROM counter WHERE k < 30
),
reasons AS (
    SELECT 1 AS n, 'digest_outside_returned_window' AS reason, 'firewall_log' AS kind
    UNION ALL SELECT 2, 'eve_rotation_lost', 'security_event'
    UNION ALL SELECT 3, 'resolver_window_not_honoured', 'dns_lookup'
)
INSERT INTO collection_gap (provider_id, interval_start_at, interval_end_at,
                            reason, detail, detected_at)
SELECT
    (SELECT id FROM provider WHERE kind = r.kind AND is_active = 1),
    :now - ((k % 5) * 3600) - ((k % 6) * 8640000) - 600,
    :now - ((k % 5) * 3600) - ((k % 6) * 8640000),
    r.reason,
    printf('gap-detail-%d', k),
    :now - ((k % 5) * 3600) - ((k % 6) * 8640000)
FROM counter
JOIN reasons AS r ON r.n = ((k - 1) % 3) + 1;

-- ---------------------------------------------------------------------------
-- Sampled measurements: the gauges and the sampled per-pair volume.
--
-- One table carries both because they are the same five facts -- a subject, a
-- measure, a unit, a value and an instant. The firewall's own telemetry names
-- no provider, because the machine reporting on itself implements no external
-- contract; the per-pair readings name the measurement provider, because that
-- volume is its material. The pair subject is the two addresses in lexicographic order joined
-- by a space, the same canonical ordering pair_volume_observation enforces, and
-- both address families appear among them.
--
-- Spread back over five months so a finite retention horizon has something to
-- remove and something to keep.
-- ---------------------------------------------------------------------------
WITH RECURSIVE counter (s) AS (
    SELECT 1
    UNION ALL
    SELECT s + 1 FROM counter WHERE s < 200
)
INSERT INTO measurement_sample (provider_id, subject_kind, subject_key, measure,
                                unit, value, sampled_at)
SELECT NULL, 'firewall', '', 'uptime_seconds', 'second', 3600.0 * s,
       :now - (s * 300) - ((s % 6) * 8640000)
FROM counter
UNION ALL
SELECT NULL, 'firewall', '', 'memory_use_ratio', 'ratio', ((s % 90) + 5) / 100.0,
       :now - (s * 300) - ((s % 6) * 8640000)
FROM counter
UNION ALL
SELECT NULL, 'firewall', printf('sensor-%d', s % 3), 'temperature_celsius', 'celsius',
       30.0 + (s % 20), :now - (s * 300) - ((s % 6) * 8640000)
FROM counter
UNION ALL
SELECT NULL, 'interface', i.device, 'bytes_in', 'byte', 1000.0 * s,
       :now - (s * 300) - ((s % 6) * 8640000)
FROM counter
JOIN interface AS i ON i.id = ((s - 1) % :interfaces) + 1
UNION ALL
SELECT
    (SELECT id FROM provider WHERE kind = 'measurement_sample' AND is_active = 1),
    'endpoint_pair',
    min(CASE WHEN s % :ipv6_every = 0 THEN local.address_v6 ELSE local.address_v4 END,
        CASE WHEN s % :ipv6_every = 0 THEN peer.address_v6 ELSE peer.address_v4 END)
    || ' ' ||
    max(CASE WHEN s % :ipv6_every = 0 THEN local.address_v6 ELSE local.address_v4 END,
        CASE WHEN s % :ipv6_every = 0 THEN peer.address_v6 ELSE peer.address_v4 END),
    'cumulative_bytes_in', 'byte', 100.0 * s,
    :now - (s * 300) - ((s % 6) * 8640000)
FROM counter
JOIN synth_address AS local ON local.slot = ((s - 1) % :clients) + 1
JOIN synth_address AS peer ON peer.slot = 1000000 + s;

-- ---------------------------------------------------------------------------
-- Reconciled state: complete sets of things, each asserted complete at an
-- instant, so that a departure is detectable.
--
-- Two sets from one provider, because one source commonly reports several and a
-- poll of one must not read as a departure of everything in the other. Each set
-- is captured several times, at 3600-second steps, walking back over the same
-- five months as everything else so the purge has rows to remove and rows to
-- leave alone.
--
-- THE MEMBERSHIP SHRINKS BY ONE EACH POLL, and that is the point rather than a
-- flourish: the newest capture of each set omits a thing its predecessor held, so
-- the departure view has something to report and a check has something to fail
-- on. The item keys are synthesised from the counter and name nothing real; the
-- attributes are a JSON object, which is the only shape that column accepts,
-- because it is read on a detail screen as fields and never aggregated.
-- ---------------------------------------------------------------------------
WITH RECURSIVE capture (k) AS (
    SELECT 1
    UNION ALL
    SELECT k + 1 FROM capture WHERE k < 12
),
sets AS (
    SELECT 'example-set-alpha' AS set_key
    UNION ALL SELECT 'example-set-beta'
)
INSERT INTO state_snapshot (provider_id, set_key, captured_at)
SELECT
    (SELECT id FROM provider WHERE kind = 'reconciled_state' AND is_active = 1),
    sets.set_key,
    :now - ((k - 1) * 3600) - ((k % 6) * 8640000)
FROM capture, sets;

-- The members. A capture holds one member for itself plus one for every capture
-- of the same set that came after it, so each successive capture holds one FEWER
-- than its predecessor: the thing whose number is highest is the one that left.
-- The count is derived from the captures' own ordering rather than from the
-- counter, so it stays correct however the instants above are spread.
WITH RECURSIVE member (n) AS (
    SELECT 1
    UNION ALL
    SELECT n + 1 FROM member WHERE n < 12
)
INSERT INTO state_item (snapshot_id, item_key, attributes, valid_until_at)
SELECT
    s.id,
    printf('example-item-%d', m.n),
    CASE WHEN m.n % 3 = 0
         THEN printf('{"example-field":"example-value-%d"}', m.n) END,
    CASE WHEN m.n % 4 = 0 THEN s.captured_at + 3600 END
FROM state_snapshot AS s, member AS m
WHERE m.n <= 1 + (
    SELECT count(*) FROM state_snapshot AS newer
    WHERE newer.provider_id = s.provider_id
      AND newer.set_key = s.set_key
      AND newer.captured_at > s.captured_at
);

DROP TABLE synth_address;

COMMIT;
